"""
DEPS Planner — Describe-Explain-Plan-Select for failure recovery.

Inspired by:
- DEPS (Wang et al., 2023, KAIST, cited 447×): Interactive planning with LLMs.
  When a plan fails, the agent DESCRIBES the situation, EXPLAINS why it failed,
  re-PLANs, and SELECTs the best plan.
- GITM (Zhu et al., 2023, Tsinghua): Sub-goal tree decomposition. High-level
  goals decomposed into a tree of sub-goals with structured actions.

DEPS maps directly to Losion's existing architecture:
- Describe: SignalExtractor classifies the current state
- Explain: ReflectionEngine generates failure explanations
- Plan: MCTS generates multiple reasoning paths
- Select: Parallel Thinking's path selection chooses the best plan

The DEPS Planner orchestrates these existing components when the agent
encounters failure, providing structured recovery instead of simple retry.

Architecture:
    Action Failure → DESCRIBE (what happened?)
                   → EXPLAIN (why did it fail?)
                   → PLAN (generate alternative approaches)
                   → SELECT (choose best plan)
                   → Execute selected plan
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class FailureType(Enum):
    """Types of failures that can occur during agent execution."""

    TOOL_FAILURE = "tool_failure"             # Tool execution failed
    SEARCH_FAILURE = "search_failure"         # Web search returned no results
    SKILL_NOT_FOUND = "skill_not_found"       # No suitable skill exists
    CONFIDENCE_DROP = "confidence_drop"       # Action reduced confidence
    TIMEOUT = "timeout"                       # Action timed out
    VALIDATION_FAILURE = "validation_failure" # Output verification failed
    CONTEXT_INSUFFICIENT = "context_insufficient"  # Retrieved context not enough


@dataclass
class FailureDescription:
    """Structured description of a failure (DEPS: Describe phase).

    Attributes:
        failure_type: Classification of the failure.
        action_taken: What action was attempted.
        expected_outcome: What was expected to happen.
        actual_outcome: What actually happened.
        confidence_before: Confidence before the failed action.
        confidence_after: Confidence after the failed action.
        domain: Domain context.
        query: The original query.
        error_details: Specific error information.
        timestamp: When the failure occurred.
    """

    failure_type: FailureType = FailureType.TOOL_FAILURE
    action_taken: str = ""
    expected_outcome: str = ""
    actual_outcome: str = ""
    confidence_before: float = 0.0
    confidence_after: float = 0.0
    domain: Optional[str] = None
    query: str = ""
    error_details: str = ""
    timestamp: float = 0.0

    def __post_init__(self) -> None:
        if self.timestamp == 0.0:
            self.timestamp = time.time()

    @property
    def confidence_delta(self) -> float:
        """Change in confidence from this failure."""
        return self.confidence_after - self.confidence_before

    @property
    def severity(self) -> float:
        """Severity of the failure [0.0, 1.0].

        Higher severity means the failure was more impactful.
        """
        # Base severity from confidence drop
        severity = abs(min(0, self.confidence_delta))

        # Increase for specific failure types
        severity_map = {
            FailureType.TIMEOUT: 0.3,
            FailureType.VALIDATION_FAILURE: 0.5,
            FailureType.CONTEXT_INSUFFICIENT: 0.2,
        }
        severity += severity_map.get(self.failure_type, 0.0)

        return min(1.0, severity)


@dataclass
class RecoveryPlan:
    """A recovery plan generated by the DEPS planner.

    Attributes:
        description: Human-readable description of the plan.
        actions: Ordered sequence of actions to execute.
        rationale: Why this plan is expected to work.
        estimated_success_rate: Expected success rate [0.0, 1.0].
        plan_type: Classification of the recovery strategy.
        fallback_plan: Optional fallback if this plan also fails.
        metadata: Additional plan metadata.
    """

    description: str = ""
    actions: List[str] = field(default_factory=list)
    rationale: str = ""
    estimated_success_rate: float = 0.5
    plan_type: str = "alternative_action"
    fallback_plan: Optional["RecoveryPlan"] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_viable(self) -> bool:
        """Whether this plan has a reasonable chance of success."""
        return self.estimated_success_rate > 0.2 and len(self.actions) > 0


class DEPSPlanner:
    """Describe-Explain-Plan-Select for structured failure recovery.

    When an agent action fails, the DEPS Planner provides structured recovery:

    1. DESCRIBE: Classify the failure type and capture what happened
    2. EXPLAIN: Generate an explanation of why the action failed
    3. PLAN: Generate multiple alternative approaches
    4. SELECT: Choose the best plan based on estimated success rate

    This is more sophisticated than simple retry because:
    - It understands WHY the failure occurred (not just THAT it occurred)
    - It generates MULTIPLE alternative plans (not just one)
    - It ESTIMATES success rates based on experience (not blind retry)
    - It provides FALLBACK plans in case the first alternative also fails

    Usage:
        planner = DEPSPlanner()
        failure = FailureDescription(
            failure_type=FailureType.SEARCH_FAILURE,
            action_taken="web_search",
            actual_outcome="No results found",
        )
        plan = planner.recover(failure)
        # plan.actions = ["skill_lookup", "tool_search"]

    Args:
        max_plans: Maximum number of recovery plans to generate.
        min_success_rate: Minimum estimated success rate for a viable plan.
    """

    # Recovery strategies by failure type
    RECOVERY_STRATEGIES: Dict[FailureType, List[Dict[str, Any]]] = {
        FailureType.SEARCH_FAILURE: [
            {
                "plan_type": "refine_query",
                "actions": ["web_search"],
                "description": "Refine the search query and retry",
                "rationale": "The search query may be too broad or ambiguous",
                "estimated_success_rate": 0.6,
            },
            {
                "plan_type": "alternative_source",
                "actions": ["skill_lookup", "web_search"],
                "description": "Try skill lookup first, then search with domain context",
                "rationale": "Existing skills may provide the answer without search",
                "estimated_success_rate": 0.5,
            },
            {
                "plan_type": "decompose_and_search",
                "actions": ["web_search", "web_search", "skill_lookup"],
                "description": "Break the query into sub-queries and search each",
                "rationale": "Complex queries may need multiple focused searches",
                "estimated_success_rate": 0.4,
            },
        ],
        FailureType.SKILL_NOT_FOUND: [
            {
                "plan_type": "create_skill",
                "actions": ["web_search", "skill_create"],
                "description": "Search for information and create a new skill",
                "rationale": "No existing skill — create one from web context",
                "estimated_success_rate": 0.7,
            },
            {
                "plan_type": "compose_skills",
                "actions": ["skill_lookup", "skill_lookup"],
                "description": "Find multiple partial skills and compose them",
                "rationale": "Individual skills may cover parts of the task",
                "estimated_success_rate": 0.4,
            },
            {
                "plan_type": "direct_tool",
                "actions": ["tool_search", "terminal_execute"],
                "description": "Use a tool directly instead of a skill",
                "rationale": "Tools can handle the task even without a skill",
                "estimated_success_rate": 0.5,
            },
        ],
        FailureType.CONFIDENCE_DROP: [
            {
                "plan_type": "verify_and_retry",
                "actions": ["verify_output", "skill_lookup"],
                "description": "Verify the current output and find supporting skills",
                "rationale": "Confidence dropped — verify and find supporting evidence",
                "estimated_success_rate": 0.5,
            },
            {
                "plan_type": "alternative_approach",
                "actions": ["tool_search", "web_search"],
                "description": "Try a completely different approach using tools",
                "rationale": "Current approach is not working — try something new",
                "estimated_success_rate": 0.4,
            },
        ],
        FailureType.TOOL_FAILURE: [
            {
                "plan_type": "fallback_tool",
                "actions": ["tool_search"],
                "description": "Find an alternative tool for the same task",
                "rationale": "The current tool failed — try a different one",
                "estimated_success_rate": 0.6,
            },
            {
                "plan_type": "create_tool",
                "actions": ["tool_create"],
                "description": "Create a custom tool for this specific task",
                "rationale": "No existing tool works — create a new one",
                "estimated_success_rate": 0.5,
            },
        ],
        FailureType.VALIDATION_FAILURE: [
            {
                "plan_type": "revise_and_verify",
                "actions": ["web_search", "verify_output"],
                "description": "Search for correct information and re-verify",
                "rationale": "Output is incorrect — find correct information first",
                "estimated_success_rate": 0.5,
            },
        ],
        FailureType.TIMEOUT: [
            {
                "plan_type": "simpler_approach",
                "actions": ["skill_lookup"],
                "description": "Use a simpler, faster approach",
                "rationale": "The action timed out — try something less expensive",
                "estimated_success_rate": 0.4,
            },
        ],
        FailureType.CONTEXT_INSUFFICIENT: [
            {
                "plan_type": "deeper_search",
                "actions": ["web_search", "web_search"],
                "description": "Search again with refined queries",
                "rationale": "Initial search was insufficient — search deeper",
                "estimated_success_rate": 0.6,
            },
            {
                "plan_type": "multi_source",
                "actions": ["web_search", "skill_lookup", "tool_search"],
                "description": "Gather information from multiple sources",
                "rationale": "One source is insufficient — combine multiple",
                "estimated_success_rate": 0.5,
            },
        ],
    }

    def __init__(
        self,
        max_plans: int = 3,
        min_success_rate: float = 0.2,
    ) -> None:
        self.max_plans = max_plans
        self.min_success_rate = min_success_rate

    def recover(
        self,
        failure: FailureDescription,
        context: Optional[List[str]] = None,
        experience: Optional[Any] = None,
    ) -> RecoveryPlan:
        """Generate a recovery plan for a failed action.

        Executes the full DEPS pipeline:
        1. Describe: Classify the failure
        2. Explain: Generate failure explanation
        3. Plan: Generate alternative approaches
        4. Select: Choose the best plan

        Args:
            failure: Description of the failure.
            context: Current context when failure occurred.
            experience: Optional episodic memory for experience-based adjustments.

        Returns:
            RecoveryPlan with the recommended recovery strategy.
        """
        # === DESCRIBE ===
        description = self._describe(failure)

        # === EXPLAIN ===
        explanation = self._explain(failure, context)

        # === PLAN ===
        plans = self._plan(failure, explanation, context)

        if not plans:
            # No recovery plans available — create a minimal fallback
            return RecoveryPlan(
                description="No recovery plans available. Falling back to model-only inference.",
                actions=[],
                rationale="All attempted actions failed. Model should rely on parametric knowledge.",
                estimated_success_rate=0.2,
                plan_type="model_fallback",
            )

        # === Adjust plans based on experience ===
        if experience is not None:
            plans = self._adjust_for_experience(plans, failure, experience)

        # === SELECT ===
        selected = self._select(plans, failure)

        return selected

    def _describe(self, failure: FailureDescription) -> str:
        """DESCRIBE phase: Create a structured description of the failure.

        Captures what happened, what was expected, and what actually occurred.
        """
        return (
            f"Failure: {failure.failure_type.value} during '{failure.action_taken}'. "
            f"Expected: {failure.expected_outcome or 'successful execution'}. "
            f"Actual: {failure.actual_outcome or 'action failed'}. "
            f"Confidence: {failure.confidence_before:.2f} → {failure.confidence_after:.2f}. "
            f"Severity: {failure.severity:.2f}."
        )

    def _explain(
        self,
        failure: FailureDescription,
        context: Optional[List[str]],
    ) -> str:
        """EXPLAIN phase: Generate an explanation of why the failure occurred.

        Uses failure type heuristics and context analysis to explain
        the root cause of the failure.
        """
        explanations = {
            FailureType.SEARCH_FAILURE: (
                f"Web search for '{failure.query}' returned no useful results. "
                f"This may be because: (1) the query is too specific or obscure, "
                f"(2) the information is not available online, "
                f"(3) the query terms don't match how the information is indexed."
            ),
            FailureType.SKILL_NOT_FOUND: (
                f"No skill found for domain '{failure.domain}' and query '{failure.query}'. "
                f"This indicates a gap in the skill library — the agent hasn't encountered "
                f"this type of task before, or the existing skills don't cover this specific need."
            ),
            FailureType.CONFIDENCE_DROP: (
                f"The action '{failure.action_taken}' reduced confidence by "
                f"{abs(failure.confidence_delta):.2f}. This suggests the action's output "
                f"was inconsistent with the model's expectations, or the retrieved information "
                f"contradicted the model's parametric knowledge."
            ),
            FailureType.TOOL_FAILURE: (
                f"Tool '{failure.action_taken}' execution failed: {failure.error_details}. "
                f"This may be due to: (1) incorrect tool parameters, "
                f"(2) tool implementation error, (3) missing dependencies."
            ),
            FailureType.VALIDATION_FAILURE: (
                f"Output verification failed after '{failure.action_taken}'. "
                f"The model's reasoning produced a result that doesn't pass "
                f"neuro-symbolic verification checks."
            ),
            FailureType.TIMEOUT: (
                f"Action '{failure.action_taken}' timed out. The operation took too long, "
                f"possibly due to: (1) complex computation, (2) slow network response, "
                f"(3) resource contention."
            ),
            FailureType.CONTEXT_INSUFFICIENT: (
                f"The retrieved context from '{failure.action_taken}' was insufficient to "
                f"answer the query. More information or different search strategies are needed."
            ),
        }

        return explanations.get(
            failure.failure_type,
            f"Action '{failure.action_taken}' failed for unknown reasons. "
            f"Confidence changed from {failure.confidence_before:.2f} to {failure.confidence_after:.2f}.",
        )

    def _plan(
        self,
        failure: FailureDescription,
        explanation: str,
        context: Optional[List[str]],
    ) -> List[RecoveryPlan]:
        """PLAN phase: Generate multiple alternative approaches.

        Looks up recovery strategies for the failure type and
        generates concrete plans with estimated success rates.
        """
        strategies = self.RECOVERY_STRATEGIES.get(failure.failure_type, [])
        plans = []

        for strategy in strategies[:self.max_plans]:
            # Adjust estimated success rate based on failure severity
            base_rate = strategy.get("estimated_success_rate", 0.5)
            adjusted_rate = base_rate * (1.0 - failure.severity * 0.3)
            adjusted_rate = max(self.min_success_rate, adjusted_rate)

            plan = RecoveryPlan(
                description=strategy.get("description", ""),
                actions=list(strategy.get("actions", [])),
                rationale=strategy.get("rationale", ""),
                estimated_success_rate=adjusted_rate,
                plan_type=strategy.get("plan_type", "alternative_action"),
                metadata={
                    "failure_type": failure.failure_type.value,
                    "explanation": explanation[:200],
                },
            )
            plans.append(plan)

        # Create chained plans with fallbacks
        if len(plans) >= 2:
            plans[0].fallback_plan = plans[1]

        return plans

    def _adjust_for_experience(
        self,
        plans: List[RecoveryPlan],
        failure: FailureDescription,
        experience: Any,
    ) -> List[RecoveryPlan]:
        """Adjust plan success rates based on past experience.

        If episodic memory shows that certain recovery strategies
        worked for similar failures in the past, boost their
        estimated success rates.
        """
        try:
            recs = experience.get_action_recommendations(
                query=failure.query,
                domain=failure.domain,
            )

            for plan in plans:
                # Check if any action in the plan has positive experience
                for action in plan.actions:
                    if action in recs:
                        # Boost success rate based on positive experience
                        boost = recs[action] * 0.1
                        plan.estimated_success_rate = min(
                            0.95, plan.estimated_success_rate + boost
                        )

        except Exception:
            pass

        return plans

    def _select(
        self,
        plans: List[RecoveryPlan],
        failure: FailureDescription,
    ) -> RecoveryPlan:
        """SELECT phase: Choose the best recovery plan.

        Selection criteria:
        1. Estimated success rate (primary)
        2. Plan simplicity (fewer actions preferred for high-severity failures)
        3. Plan type match (some plan types are better for certain failures)

        Returns:
            The best RecoveryPlan from the candidates.
        """
        if not plans:
            return RecoveryPlan(
                description="No plans available",
                actions=[],
                estimated_success_rate=0.0,
            )

        # Filter viable plans
        viable = [p for p in plans if p.is_viable]

        if not viable:
            # All plans are below minimum success rate — pick the best one
            viable = plans

        # Sort by estimated success rate (descending)
        viable.sort(key=lambda p: p.estimated_success_rate, reverse=True)

        # For high-severity failures, prefer simpler plans
        if failure.severity > 0.5:
            # Re-sort: balance success rate with simplicity
            viable.sort(
                key=lambda p: p.estimated_success_rate / (1 + len(p.actions) * 0.1),
                reverse=True,
            )

        selected = viable[0]
        logger.info(
            f"DEPS recovery: {selected.plan_type} "
            f"(success_rate={selected.estimated_success_rate:.2f}, "
            f"actions={selected.actions})"
        )

        return selected
